### ISSUE TITLE
Issue with gathering facts on AOS 8

### ISSUE THREAD

**Issue by aturbin-35** [gmoisio/gmoisio.ale#2]
Hello,
First of all, thank you for this collection.
I'm trying to use the gathering fact task and I'm facing an issue related to netmiko.
The playbook is simple :
```
---

- name: Main playbook
  hosts: all
  connection: local
  gather_facts: false
  tasks:
      gmoisio.ale.ale_aos_facts:
            host: "{{ ansible_host }}"
            username: ####
            password: ####
            getters:
            - vlans
            - interfaces
            - ntp
```

I installed cerberus and netmiko.
When I run the playbook, I receive an error saying roughly "no module named netmiko".
A pip freeze confirm that netmiko and cerberus are installed.

On the switch, I can see the following lines when I run the playbook:
```
Jan 19 04:29:20 b03234net sshd[3671]: Accepted keyboard-interactive/pam for <user> from X.X.X.X port 50855 ssh2
Jan 19 04:29:21 b03234net swlogd: SES CMD alarm(1) CLI log, user: <user>(X.X.X.X), cmd: uname; echo FOUND; command -v ""'""/usr/bin/python""'""; command -v ""'""python3.9""'"
Jan 19 04:29:22 b03234net sshd[3671]: subsystem request for sftp by user <user>
Jan 19 04:29:23 b03234net swlogd: SES CMD alarm(1) CLI log, user: <user> (X.X.X.X), cmd: sudo -H -S -n -u root /bin/sh -c echo BECOME-SUCCESS-nzthelkwahfckquflksihysgkjylszps

```

It seems like it tries to find netmiko on the switch but I'm not sure.

Any suggestions ?

Thank you

**Comment by gmoisio** [comment]
Hi thank you for your message.

I did a test with a Python virtual environment into which all the requirements were installed.
I used this playbook with success.

```
---
- name: This is a test for ale_aos_facts module
  hosts: ale
  connection: local
  gather_facts: no
  tasks:
    - name: Test ale_aos_facts Python module
      gmoisio.ale.ale_aos_facts: 
        host: "{{ ansible_host }}"
        username: "{{ login }}"
        password: "{{ password }}"
        getters:
          - vlans
          - interfaces
          - ntp
      register: get_facts
    - ansible.builtin.debug:
        msg: "vlan ID: {{ item }}"
      loop: "{{ get_facts.output.vlans }}"
    - ansible.builtin.debug:
        msg: "Interface: {{ item }}"
      loop: "{{ get_facts.output.interfaces }}"
```

There is no reason for the playbook to send any Python program to the switch...
Regards
